export const STRIPE_COUNTRIES = [
  { id: 'AR', value: 'Argentina (AR)' },
  { id: 'AU', value: 'Australia (AU)' },
  { id: 'AT', value: 'Austria (AT)' },
  { id: 'BE', value: 'Belgium (BE)' },
  { id: 'BO', value: 'Bolivia (BO)' },
  { id: 'BA', value: 'Bosnia & Herzegovina (BA)' },
  { id: 'BR', value: 'Brazil (BR)' },
  { id: 'BG', value: 'Bulgaria (BG)' },
  { id: 'CA', value: 'Canada (CA)' },
  { id: 'CL', value: 'Chile (CL)' },
  { id: 'CO', value: 'Colombia (CO)' },
  { id: 'CR', value: 'Costa Rica (CR)' },
  { id: 'HR', value: 'Croatia (HR)' },
  { id: 'CY', value: 'Cyprus (CY)' },
  { id: 'CZ', value: 'Czech Republic (CZ)' },
  { id: 'DK', value: 'Denmark (DK)' },
  { id: 'DO', value: 'Dominican Republic (DO)' },
  { id: 'EC', value: 'Ecuador (EC)' },
  { id: 'EG', value: 'Egypt (EG)' },
  { id: 'SV', value: 'El Salvador (SV)' },
  { id: 'EE', value: 'Estonia (EE)' },
  { id: 'FI', value: 'Finland (FI)' },
  { id: 'FR', value: 'France (FR)' },
  { id: 'DE', value: 'Germany (DE)' },
  { id: 'GH', value: 'Ghana (GH)' },
  { id: 'GR', value: 'Greece (GR)' },
  { id: 'GT', value: 'Guatemala (GT)' },
  { id: 'HK', value: 'Hong Kong (HK)' },
  { id: 'HU', value: 'Hungary (HU)' },
  { id: 'IN', value: 'India (IN)' },
  { id: 'ID', value: 'Indonesia (ID)' },
  { id: 'IE', value: 'Ireland (IE)' },
  { id: 'IL', value: 'Israel (IL)' },
  { id: 'IT', value: 'Italy (IT)' },
  { id: 'JP', value: 'Japan (JP)' },
  { id: 'JO', value: 'Jordan (JO)' },
  { id: 'KE', value: 'Kenya (KE)' },
  { id: 'LV', value: 'Latvia (LV)' },
  { id: 'LT', value: 'Lithuania (LT)' },
  { id: 'LU', value: 'Luxembourg (LU)' },
  { id: 'MY', value: 'Malaysia (MY)' },
  { id: 'MT', value: 'Malta (MT)' },
  { id: 'MX', value: 'Mexico (MX)' },
  { id: 'MD', value: 'Moldova (MD)' },
  { id: 'MA', value: 'Morocco (MA)' },
  { id: 'NL', value: 'Netherlands (NL)' },
  { id: 'NZ', value: 'New Zealand (NZ)' },
  { id: 'NG', value: 'Nigeria (NG)' },
  { id: 'MK', value: 'North Macedonia (MK)' },
  { id: 'NO', value: 'Norway (NO)' },
  { id: 'PK', value: 'Pakistan (PK)' },
  { id: 'PA', value: 'Panama (PA)' },
  { id: 'PE', value: 'Peru (PE)' },
  { id: 'PH', value: 'Philippines (PH)' },
  { id: 'PL', value: 'Poland (PL)' },
  { id: 'PT', value: 'Portugal (PT)' },
  { id: 'QA', value: 'Qatar (QA)' },
  { id: 'RO', value: 'Romania (RO)' },
  { id: 'SA', value: 'Saudi Arabia (SA)' },
  { id: 'RS', value: 'Serbia (RS)' },
  { id: 'SG', value: 'Singapore (SG)' },
  { id: 'SK', value: 'Slovakia (SK)' },
  { id: 'SI', value: 'Slovenia (SI)' },
  { id: 'ZA', value: 'South Africa (ZA)' },
  { id: 'KR', value: 'South Korea (KR)' },
  { id: 'ES', value: 'Spain (ES)' },
  { id: 'SE', value: 'Sweden (SE)' },
  { id: 'CH', value: 'Switzerland (CH)' },
  { id: 'TW', value: 'Taiwan (TW)' },
  { id: 'TH', value: 'Thailand (TH)' },
  { id: 'TR', value: 'Turkey (TR)' },
  { id: 'UA', value: 'Ukraine (UA)' },
  { id: 'AE', value: 'United Arab Emirates (AE)' },
  { id: 'GB', value: 'United Kingdom (GB)' },
  { id: 'US', value: 'United States (US)' },
  { id: 'UY', value: 'Uruguay (UY)' },
  { id: 'VN', value: 'Vietnam (VN)' },
];
